/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE CandidateSurveyBase PLEASE EDIT ../candidate-survey.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Survey } from '../survey';

/**
 * This is the model of CandidateSurvey object
 *
 */
export class CandidateSurveyBase {

    constructor() { }

    public _id: string;
    public CandidateId?: string;
    public Comments?: string;
    public CompletionDate?: Date;
    public Response?: string;
    public Status?: string;
    public SurveyId?: string;
    public SurveyQuestions?: string;
    // Relations Survey
    public Survey: Survey | string;
}
