/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE CandidateBase PLEASE EDIT ../candidate.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

/**
 * This is the model of Candidate object
 *
 */
export class CandidateBase {

    constructor() { }

    public _id: string;
    public AppointmentDate?: Date;
    public AppointmentId?: string;
    public AppointmentResults?: string;
    public AppointmentStatus?: string;
    public ConversionFrom?: string;
    public DeferReason?: string;
    public DeferredDate?: Date;
    public Email?: string;
    public FirstName?: string;
    public HireDate?: Date;
    public Hired?: Boolean;
    public LastName?: string;
    public MiddleName?: string;
    public Recruiter?: string;
    public ReferredBy?: string;
    public SAPUser?: string;
    // Relations m:m Positions
    public Positions: string[]}
