/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE TaskBase PLEASE EDIT ../task.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

/**
 * This is the model of Task object
 *
 */
export class TaskBase {

    constructor() { }

    public _id: string;
    public AssignedTo?: string;
    public Comments?: string;
    public DaysAllowed?: number;
    public DueDate?: Date;
    public Status?: string;
    public TaskDescription?: string;
    public TaskLink?: string;
    public TaskName?: string;
    public TaskOwner?: string;
    // Relations m:m TaskList
    public TaskList: string[]}
