/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE candidate-notificationBaseService PLEASE EDIT ../candidate-notification.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { CandidateNotification } from '../../domain/easy-recruit-demo_db/candidate-notification';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../CandidateNotification.service.ts
 */

/*
 * SCHEMA DB CandidateNotification
 *
	{
		CandidateId: {
			type: 'String'
		},
		Email: {
			type: 'String'
		},
		Message: {
			type: 'String'
		},
		Method: {
			type: 'String'
		},
		Phone: {
			type: 'String'
		},
		SendDate: {
			type: 'Date'
		},
		Status: {
			type: 'String'
		},
		Title: {
			type: 'String'
		},
		Type: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Candidate: {
			type: Schema.ObjectId,
			ref : "CandidateNotification"
		},
	}
 *
 */
@Injectable()
export class CandidateNotificationBaseService {

    contextUrl: string = environment.endpoint + '/notifications';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * CandidateNotificationService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: CandidateNotification): Observable<CandidateNotification> {
        return this.http
            .post<CandidateNotification>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * CandidateNotificationService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CandidateNotificationService.findByCandidate
    *   @description CRUD ACTION findByCandidate
    *   @param Objectid key Id della risorsa Candidate da cercare
    *
    */
    findByCandidate(id: string): Observable<CandidateNotification[]> {
        return this.http
            .get<CandidateNotification[]>(this.contextUrl + '/findByCandidate/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * CandidateNotificationService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<CandidateNotification> {
        return this.http
            .get<CandidateNotification>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CandidateNotificationService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<CandidateNotification[]> {
        return this.http
            .get<CandidateNotification[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * CandidateNotificationService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: CandidateNotification): Observable<CandidateNotification> {
        return this.http
            .post<CandidateNotification>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
