/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE candidate-surveyBaseService PLEASE EDIT ../candidate-survey.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { CandidateSurvey } from '../../domain/easy-recruit-demo_db/candidate-survey';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../CandidateSurvey.service.ts
 */

/*
 * SCHEMA DB CandidateSurvey
 *
	{
		CandidateId: {
			type: 'String'
		},
		Comments: {
			type: 'String'
		},
		CompletionDate: {
			type: 'Date'
		},
		Response: {
			type: 'String'
		},
		Status: {
			type: 'String'
		},
		SurveyId: {
			type: 'String'
		},
		SurveyQuestions: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Survey: {
			type: Schema.ObjectId,
			ref : "CandidateSurvey"
		},
	}
 *
 */
@Injectable()
export class CandidateSurveyBaseService {

    contextUrl: string = environment.endpoint + '/candidatesurvey';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * CandidateSurveyService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: CandidateSurvey): Observable<CandidateSurvey> {
        return this.http
            .post<CandidateSurvey>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * CandidateSurveyService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CandidateSurveyService.findByCandidate
    *   @description CRUD ACTION findByCandidate
    *   @param Objectid key Id della risorsa Candidate da cercare
    *
    */
    findByCandidate(id: string): Observable<CandidateSurvey[]> {
        return this.http
            .get<CandidateSurvey[]>(this.contextUrl + '/findByCandidate/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * CandidateSurveyService.findBySurvey
    *   @description CRUD ACTION findBySurvey
    *   @param Objectid key Id della risorsa Survey da cercare
    *
    */
    findBySurvey(id: string): Observable<CandidateSurvey[]> {
        return this.http
            .get<CandidateSurvey[]>(this.contextUrl + '/findBySurvey/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * CandidateSurveyService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<CandidateSurvey> {
        return this.http
            .get<CandidateSurvey>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CandidateSurveyService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<CandidateSurvey[]> {
        return this.http
            .get<CandidateSurvey[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * CandidateSurveyService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: CandidateSurvey): Observable<CandidateSurvey> {
        return this.http
            .post<CandidateSurvey>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
