/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE role-permissionBaseService PLEASE EDIT ../role-permission.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { RolePermission } from '../../domain/easy-recruit-demo_db/role-permission';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../RolePermission.service.ts
 */

/*
 * SCHEMA DB RolePermission
 *
	{
		Permissions: {
			type: 'String'
		},
		RoleName: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class RolePermissionBaseService {

    contextUrl: string = environment.endpoint + '/rolepermissions';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * RolePermissionService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: RolePermission): Observable<RolePermission> {
        return this.http
            .post<RolePermission>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * RolePermissionService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * RolePermissionService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<RolePermission> {
        return this.http
            .get<RolePermission>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * RolePermissionService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<RolePermission[]> {
        return this.http
            .get<RolePermission[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * RolePermissionService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: RolePermission): Observable<RolePermission> {
        return this.http
            .post<RolePermission>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
