/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE task-listBaseService PLEASE EDIT ../task-list.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { TaskList } from '../../domain/easy-recruit-demo_db/task-list';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../TaskList.service.ts
 */

/*
 * SCHEMA DB TaskList
 *
	{
		Comments: {
			type: 'String'
		},
		TaskDescription: {
			type: 'String'
		},
		TaskListName: {
			type: 'String'
		},
		TaskName: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Positions: [{
			type: Schema.ObjectId,
			ref : "TaskList"
		}],
		TaskList: [{
			type: Schema.ObjectId,
			ref : "Task"
		}],
		TaskLists: [{
			type: Schema.ObjectId,
			ref : "Position"
		}],
	}
 *
 */
@Injectable()
export class TaskListBaseService {

    contextUrl: string = environment.endpoint + '/tasklist';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * TaskListService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: TaskList): Observable<TaskList> {
        return this.http
            .post<TaskList>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * TaskListService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TaskListService.findByPositions
    *   @description CRUD ACTION findByPositions
    *   @param Objectid key Id della risorsa Positions da cercare
    *
    */
    findByPositions(id: string): Observable<TaskList[]> {
        return this.http
            .get<TaskList[]>(this.contextUrl + '/findByPositions/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * TaskListService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<TaskList> {
        return this.http
            .get<TaskList>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TaskListService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<TaskList[]> {
        return this.http
            .get<TaskList[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * TaskListService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: TaskList): Observable<TaskList> {
        return this.http
            .post<TaskList>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
