/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE taskBaseService PLEASE EDIT ../task.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Task } from '../../domain/easy-recruit-demo_db/task';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Task.service.ts
 */

/*
 * SCHEMA DB Task
 *
	{
		AssignedTo: {
			type: 'String'
		},
		Comments: {
			type: 'String'
		},
		DaysAllowed: {
			type: 'Integer'
		},
		DueDate: {
			type: 'Date'
		},
		Status: {
			type: 'String'
		},
		TaskDescription: {
			type: 'String'
		},
		TaskLink: {
			type: 'String'
		},
		TaskName: {
			type: 'String'
		},
		TaskOwner: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Task: {
			type: Schema.ObjectId,
			ref : "Document"
		},
		TaskList: [{
			type: Schema.ObjectId,
			ref : "Task"
		}],
	}
 *
 */
@Injectable()
export class TaskBaseService {

    contextUrl: string = environment.endpoint + '/tasks';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * TaskService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Task): Observable<Task> {
        return this.http
            .post<Task>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * TaskService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TaskService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Task> {
        return this.http
            .get<Task>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TaskService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Task[]> {
        return this.http
            .get<Task[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * TaskService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Task): Observable<Task> {
        return this.http
            .post<Task>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
