/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE user-notificationBaseService PLEASE EDIT ../user-notification.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { UserNotification } from '../../domain/easy-recruit-demo_db/user-notification';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../UserNotification.service.ts
 */

/*
 * SCHEMA DB UserNotification
 *
	{
		Email: {
			type: 'String'
		},
		Message: {
			type: 'String'
		},
		Method: {
			type: 'String'
		},
		Phone: {
			type: 'String'
		},
		SendDate: {
			type: 'Date'
		},
		Status: {
			type: 'String'
		},
		Title: {
			type: 'String'
		},
		Type: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		User: {
			type: Schema.ObjectId,
			ref : "UserNotification"
		},
	}
 *
 */
@Injectable()
export class UserNotificationBaseService {

    contextUrl: string = environment.endpoint + '/usernotifications';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * UserNotificationService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: UserNotification): Observable<UserNotification> {
        return this.http
            .post<UserNotification>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * UserNotificationService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * UserNotificationService.findByUser
    *   @description CRUD ACTION findByUser
    *   @param Objectid key Id della risorsa User da cercare
    *
    */
    findByUser(id: string): Observable<UserNotification[]> {
        return this.http
            .get<UserNotification[]>(this.contextUrl + '/findByUser/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * UserNotificationService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<UserNotification> {
        return this.http
            .get<UserNotification>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * UserNotificationService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<UserNotification[]> {
        return this.http
            .get<UserNotification[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * UserNotificationService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: UserNotification): Observable<UserNotification> {
        return this.http
            .post<UserNotification>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
